[package]
name = "kv260_imx219_of_measuring_rpu"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pudding-pac = "0.1.3"

[build-dependencies]
cc = "1.0.36"
