[package]
name = "ultra96v2_udmabuf_sample"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uio = "0.2.0"
delegate = "0.6.1"