[package]
name = "jelly-rtos"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pudding-pac = { version="0.1.3" }

[features]
default = []
reg64bit = []
ercd = []

[build-dependencies]
cc = "1.0.36"
